### ISSUE TITLE
Error enabling plugin

### ISSUE THREAD

**Issue by Pawned** [the-obsidian/DiscordBridge#20]
Hey Jacob,

Thanks a lot for updating the plugin and implementing a majority of people's feature requests, always great to have a developer which responds to feedback.

I have just downloaded your latest version of the plugin in the hopes of getting the bot back online but unfortunately the plugin is failing to enable with the following error:

`[19:59:45] [Server thread/ERROR]: Error occurred while enabling DiscordBridge v1.4.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.apache.commons.logging.LogFactory.getClassLoader(Ljava/lang/Class;)Ljava/lang/ClassLoader;
    at org.apache.commons.logging.impl.LogFactoryImpl.getClassLoader(LogFactoryImpl.java:392) ~[?:?]
    at org.apache.commons.logging.impl.LogFactoryImpl.initDiagnostics(LogFactoryImpl.java:420) ~[?:?]
    at org.apache.commons.logging.impl.LogFactoryImpl.<init>(LogFactoryImpl.java:87) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_66]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_66]
    at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_66]
    at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:531) ~[?:?]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
    at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:517) ~[?:?]
    at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:316) ~[?:?]
    at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:351) ~[?:?]
    at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:89) ~[?:?]
    at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:40) ~[?:?]
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:126) ~[?:?]
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:98) ~[?:?]
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:105) ~[?:?]
    at com.mashape.unirest.http.options.Options.refresh(Options.java:72) ~[?:?]
    at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46) ~[?:?]
    at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151) ~[?:?]
    at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131) ~[?:?]
    at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56) ~[?:?]
    at net.dv8tion.jda.requests.Requester.toObject(Requester.java:97) ~[?:?]
    at net.dv8tion.jda.requests.Requester.post(Requester.java:51) ~[?:?]
    at net.dv8tion.jda.entities.impl.JDAImpl.login(JDAImpl.java:143) ~[?:?]
    at net.dv8tion.jda.JDABuilder.build(JDABuilder.java:231) ~[?:?]
    at gg.obsidian.discordbridge.DiscordConnection.<init>(DiscordConnection.kt:8) ~[?:?]
    at gg.obsidian.discordbridge.Plugin.onEnable(Plugin.kt:13) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]`

**Comment by jacobwgillespie** [comment]
What version of Spigot, Java, etc do you have?

**Comment by Pawned** [comment]
Am running git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) with Java 1.8.0_66

**Comment by jacobwgillespie** [comment]
Darn, was hoping for an easy solution...  Can you try running with as the only plugin on a copy of Spigot?  Or perhaps see if an different Spigot build works?  I'll keep digging on my end.

**Comment by Pawned** [comment]
Ok it's definitely a conflict with another plugin that is stopping it from loading. Working through my plugins now to find the culprit.

**Comment by Pawned** [comment]
Okay so I've spent a good hour or so trying to pinpoint what exactly the conflict is here but it seems to be incompatible with certain combinations of plugins... For example I have the attached zip file here and removing any one of these plugins enables Discordbridge to run so I thought "yay, I can just disable ChestIcons, that's only cosmetic" which worked in this small test environment, but then when adding my server's extra 60 odd plugins into the mix the error throws up again. So it seems that certain combinations of plugins (using any of the plugins by themselves with just Discordbridge works fine, it's when there's a certain mix of them that DiscordBridge stops) cause Discordbridge to break.

[plugins.zip](https://github.com/the-obsidian/DiscordBridge/files/122894/plugins.zip)

So this only makes things even more complicated, but I imagine the issues boils down to the new API you're using as the previous versions of DiscordBridge were fine...

**Comment by Pawned** [comment]
Okay did some more digging and found out that it was SpaceBukkit and RemoteToolkitPlugin causing Discordbridge to not work, but only if they were loaded before Discordbridge. For some reason depending on the amount of plugins on the server it would change the load order of these plugins.

So I simply added

> loadbefore: [SpaceBukkit, RemoteToolkitPlugin]

to the plugin.yml and this has now fixed the issue.

**Comment by jacobwgillespie** [comment]
Ah, cool - thanks for the PR.  Yeah, the new API library uses Unirest for HTTP calls which in turn has certain dependencies that appear to conflict with other plugins.  If I knew more about Java / packaging JARs, I wonder if there'd be a way to bundle the dependencies and sub-dependencies better, but for now this is a good quick solution.  :)  I'll release a new version.
