### ISSUE TITLE
Json-parse error

### ISSUE THREAD

**Issue by klsmith** [the-obsidian/DiscordBridge#26]
Getting the following error upon starting the server (xxxxxx's in place of server id)
`[18:23:18 INFO]: Done (5.481s)! For help, type "help" or "?"
[18:23:18 WARN]: Got an unexpected Json-parse error. Please redirect following message to the devs:
[18:23:18 WARN]:    JSONObject["muted_channels"] not found.
[18:23:18 WARN]:    READY -> {"user_settings":{"inline_embed_media":true,"render_embeds":true,"inline_attachment_media":true,"show_current_game":true,"theme":"light","enable_tts_command":true,"locale":"en-US","convert_emoticons":true,"message_display_compact":false},"read_state":[{"last_message_id":"150378756211605515","mention_count":0,"id":"xxxxxxxxx"}],"guilds":[{"emojis":[],"large":false,"owner_id":"147064481174913024","roles":[{"color":0,"permissions":36916224,"managed":false,"name":"@everyone","position":-1,"id":"147064712914272256","hoist":false},{"color":3447003,"permissions":36953089,"managed":false,"name":"@member","position":1,"id":"147070029945372672","hoist":false},{"color":10181046,"permissions":66321471,"managed":false,"name":"@admin","position":2,"id":"147070369830797312","hoist":true},{"color":1752220,"permissions":32767039,"managed":false,"name":"@bot","position":3,"id":"147782444890718208","hoist":true}],"icon":"03316366db64017ece188b6570b41477","afk_timeout":300,"joined_at":"2016-02-12T18:28:45.808000+00:00","features":[],"verification_level":0,"presences":[{"game":{"name":"Minecraft"},"user":{"id":"146393892600807424"},"status":"online"},{"game":null,"user":{"id":"147064481174913024"},"status":"online"},{"game":null,"user":{"id":"147453396251574273"},"status":"idle"},{"game":null,"user":{"id":"147769503931957248"},"status":"online"}],"channels":[{"permission_overwrites":[],"last_message_id":"150379663598944257","name":"general","topic":"","position":0,"id":"147064712914272256","type":"text"},{"permission_overwrites":[{"allow":0,"deny":0,"id":"147064712914272256","type":"role"}],"last_message_id":null,"name":"General","bitrate":64000,"position":0,"id":"147064712914272257","type":"voice"}],"afk_channel_id":null,"members":[{"joined_at":"2016-02-10T22:01:19.555000+00:00","roles":["147070029945372672"],"deaf":false,"mute":false,"user":{"id":"146393892600807424","avatar":null,"username":"Wiseman333","discriminator":"5954"}},{"joined_at":"2016-02-10T19:46:47.024000+00:00","roles":["147070029945372672"],"deaf":false,"mute":false,"user":{"id":"146460644563091457","avatar":null,"username":"deadpixel88","discriminator":"2017"}},{"joined_at":"2016-02-10T19:42:39.891000+00:00","roles":["147070369830797312"],"deaf":false,"mute":false,"user":{"id":"147064481174913024","avatar":"717ee368c3dc66cf8f4f1858c43a9211","username":"Sivalion","discriminator":"3642"}},{"joined_at":"2016-02-13T02:26:45.833000+00:00","roles":["147070029945372672"],"deaf":false,"mute":false,"user":{"id":"147453396251574273","avatar":"cb07b68d624ec4465bd7cb7fd0c41fcf","username":"Ashzilla","discriminator":"1425"}},{"joined_at":"2016-02-12T04:48:06.449000+00:00","roles":["147070029945372672"],"deaf":false,"mute":false,"user":{"id":"147562981063000065","avatar":null,"username":"Hades4614","discriminator":"0335"}},{"joined_at":"2016-02-12T18:28:45.808000+00:00","roles":["147782444890718208"],"deaf":false,"mute":false,"user":{"id":"147769503931957248","avatar":null,"username":"kupocraft","discriminator":"5285"}},{"joined_at":"2016-02-15T05:25:08.241000+00:00","roles":["147070029945372672"],"deaf":false,"mute":false,"user":{"id":"148655754084220928","avatar":null,"username":"zuroko","discriminator":"8682"}}],"name":"Kupocraft Chat","voice_states":[{"self_deaf":false,"user_id":"147064481174913024","deaf":false,"session_id":"5310caebd0c51b2e233170c7dd8ffc54","mute":false,"suppress":false,"self_mute":true,"channel_id":"147064712914272257"}],"id":"147064712914272256","region":"us-east","member_count":7,"splash":null}],"v":3,"user_guild_settings":[],"session_id":"89a4dfd6def4935e795bb52ceab14dc5","private_channels":[],"tutorial":null,"user":{"verified":true,"id":"147769503931957248","avatar":null,"email":"kupocraft@gmail.com","username":"kupocraft","discriminator":"5285"},"heartbeat_interval":41250}`

and then I get the following error when someone attempts to type from the discord app (nothing happens when they type in minecraft).
`[18:34:26 WARN]: JDA encountered an internal error.
[18:34:26 WARN]: java.lang.IllegalArgumentException: Could not find Private Channel of id xxxxxxxxxxxxx
[18:34:26 WARN]:    at net.dv8tion.jda.handle.EntityBuilder.createMessage(EntityBuilder.java:349)
[18:34:26 WARN]:    at net.dv8tion.jda.handle.MessageReceivedHandler.handle(MessageReceivedHandler.java:42)
[18:34:26 WARN]:    at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:141)
[18:34:26 WARN]:    at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
[18:34:26 WARN]:    at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
[18:34:26 WARN]:    at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
[18:34:26 WARN]:    at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
[18:34:26 WARN]:    at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
[18:34:26 WARN]:    at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
[18:34:26 WARN]:    at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)`

**Comment by Paul--** [comment]
I'm getting exactly this error too! Updating to the latest version didn't help.

**Comment by jacobwgillespie** [comment]
Yep, looks like Discord updated their API - I'll push out a version (`1.4.2`) with an updated API client library.  I'll test it later today, though feel free to test yourself and report back here if that resolves the issue.

**Comment by Paul--** [comment]
I've tested 1.4.2 once, and so far no problems. Thanks for taking care of this so quickly! Must be annoying having to update so often - Discord pushes out their own updates pretty frequently.

**Comment by jacobwgillespie** [comment]
Sweet!  I hit an issue testing 1.4.2 so I'm pushing out 1.4.3 now so I can test.  Thankfully the upstream API client updates fairly frequently, so not a ton of work on my part.  :)  Looking forward to official Discord APIs though...

**Comment by jacobwgillespie** [comment]
1.4.3 failed to build - 1.4.4 is out now and should resolve this issue.
