### ISSUE TITLE
GLIBC_2.14 not found

### ISSUE THREAD

**Issue by Pawned** [the-obsidian/DiscordBridge#27]
Hey Jacob,

Got another problem now we have another Discord update haha.

Reading the error it looks like it might be specific to Linux, but I have yet to try on Windows yet. Not sure what exactly this file is it's trying to open, but I'm guessing it wasn't required in the previous version of the API you were using.

I'm going to try on my local Windows test server now and will post feedback.

`[22:32:13] [Server thread/INFO]: [DiscordBridge] Enabling DiscordBridge v1.4.2
[22:32:13] [Server thread/ERROR]: Error occurred while enabling DiscordBridge v1.4.2 (Is it up to date?)
java.lang.UnsatisfiedLinkError: /tmp/libopus6170821543746543181.so: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.14' not found (required by /tmp/libopus6170821543746543181.so)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_66]
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938) ~[?:1.8.0_66]
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821) ~[?:1.8.0_66]
    at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_66]
    at java.lang.System.load(System.java:1086) ~[?:1.8.0_66]
    at net.dv8tion.jda.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:121) ~[?:?]
    at net.dv8tion.jda.managers.AudioManager.<clinit>(AudioManager.java:311) ~[?:?]
    at net.dv8tion.jda.entities.impl.JDAImpl.<init>(JDAImpl.java:62) ~[?:?]
    at net.dv8tion.jda.JDABuilder.buildAsync(JDABuilder.java:235) ~[?:?]
    at net.dv8tion.jda.JDABuilder.build(JDABuilder.java:209) ~[?:?]
    at gg.obsidian.discordbridge.DiscordConnection.<init>(DiscordConnection.kt:8) ~[?:?]
    at gg.obsidian.discordbridge.Plugin.onEnable(Plugin.kt:13) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]`

**Comment by Pawned** [comment]
Just tested on Windows running the exact same plugins, and Spigot and no problem. So this is likely an issue with the API and Linux.

**Comment by Pawned** [comment]
Manually compiled version 1.4.3 of your plugin and can confirm this resolves the issue.

**Comment by jacobwgillespie** [comment]
Sweet, yeah, 1.4.3 is supposed to fix this issue.  It failed to build, so 1.4.4 is out now (fixing that and another bug).
