### ISSUE TITLE
Version 3.0.0 drops a lot of relayed messages. 

### ISSUE THREAD

**Issue by CatPasswd** [the-obsidian/DiscordBridge#53]
I installed the 3.0.0 plugin last night, and it appears to run just fine.  However, message relay is hit-or-miss. Fully half the messages don't get passed in either direction. Here's an example error message from the log. 

[02:57:46] [Craft Scheduler Thread - 13/INFO]: [DiscordBridge] Entered relay. event: wait what y tho
[02:58:04] [ReadingThread/INFO]: [DiscordBridge] Entered relay. event: Idk he just went "wait wAITWAITWAITGO BACK"
[02:58:04] [ReadingThread/WARN]: [02:58:04] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[02:58:04] [ReadingThread/WARN]: [02:58:04] [Fatal] [JDA]: Encountered an exception:
[02:58:04] [ReadingThread/WARN]: [02:58:04] [Fatal] [JDA]: java.lang.IllegalStateException: Asynchronous entity track!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
        at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:108)
        at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:82)
        at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21)
        at net.minecraft.server.v1_12_R1.World.b(World.java:1093)
        at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1160)
        at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1125)
        at net.minecraft.server.v1_12_R1.Chunk.addEntities(Chunk.java:753)
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
        at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:331)
        at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:327)
        at net.minecraft.server.v1_12_R1.World.getType(World.java:808)
        at net.minecraft.server.v1_12_R1.TileEntityCommand$1.i(TileEntityCommand.java:33)
        at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:331)
        at org.bukkit.craftbukkit.v1_12_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcast(CraftServer.java:1268)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcastMessage(CraftServer.java:451)
        at gg.obsidian.discordbridge.Plugin.sendToMinecraft(Plugin.kt:112)
        at gg.obsidian.discordbridge.commands.controllers.BotControllerManager.relay(BotControllerManager.kt:390)
        at gg.obsidian.discordbridge.commands.controllers.BotControllerManager.dispatchMessage(BotControllerManager.kt:149)
        at gg.obsidian.discordbridge.discord.Listener.onMessageReceived(Listener.kt:39)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:327)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:129)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:51)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)

**Comment by CatPasswd** [comment]
Update: This only happens on Discord ---> MC. The other direction doesn't seem to have a problem relaying.

**Comment by DiamondIceNS** [comment]
I can't seem to reproduce this, is it still happening?
