### ISSUE TITLE
DiscordBridge 3.1.0 not recognizing multiverse world name

### ISSUE THREAD

**Issue by ldilley** [the-obsidian/DiscordBridge#61]
Using the latest Spigot release (1.12.2) with the latest Multiverse-Core release (2.5.0) and DiscordBridge (3.1.0) results in a failure to send messages to Discord when these messages contain a multiverse world name (using "%w"). Chatting in the base world works as expected. Steps to reproduce:

1.) `/mv create test normal`
2.) `/mv tp test`
3.) Type and send a message such as: "Test message"

The relevant line in config.yml looks like:
`chat-message: <%u@server:%w> %m`

This formerly worked in previous versions. The following stack trace is also produced each time a message is sent from a multiverse world:

`[23:05:41] [Server thread/INFO]: JonDough issued server command: /mv create test normal`

`[23:05:41] [Server thread/INFO]: JonDough: Starting creation of world 'test'...`

`[23:06:09] [Server thread/INFO]: [Multiverse-Core] New Spawn for 'test' is located at: test:65.50,68.00,236.50:0.00:0.00`

`[23:06:10] [Server thread/INFO]: JonDough: Complete!`

`[23:07:43] [Server thread/INFO]: JonDough issued server command: /mv tp test`

`[23:07:57] [Async Chat Thread - #9/INFO]: [test]<JonDough> test message!`

>[23:07:57] [Craft Scheduler Thread - 111/WARN]: [DiscordBridge] Plugin DiscordBridge v3.1.0-dev1 generated an exception while executing task 5311
java.lang.NullPointerException: null
        at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at gg.obsidian.discordbridge.commands.controllers.BotControllerManager.relay(BotControllerManager.kt:429) ~[?:?]
        at gg.obsidian.discordbridge.commands.controllers.BotControllerManager.dispatchMessage(BotControllerManager.kt:130) ~[?:?]
        at gg.obsidian.discordbridge.minecraft.EventListener$onChat$1.run(EventListener.kt:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-109b080-ab09b27]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-109b080-ab09b27]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by DiamondIceNS** [comment]
I believe the current version of DiscordBridge has a bug where you'll get this sort of crash when the Multiverse world you're in doesn't have a registered alias. Could you test to see if that's the case by using `/mvm set alias TestWorld` to see if the issue goes away?

I'll look into solving this bug in the meantime.

**Comment by ldilley** [comment]
Thank you for the prompt response, @DiamondIceNS. Assigning an alias to a multiverse world does indeed prevent the stack trace from appearing and also allows for the receipt of the message in Discord. "%w" still does not get expanded to the world or alias name however. The output looks like this in Discord:
`<JonDough@server:> test message`

The expected output should be:
`<JonDough@server:plotworld> test message`

Please let me know if you require anything else.

**Comment by DiamondIceNS** [comment]
For some reason Minecraft is crashing on startup on my PC due to some OpenGL issues so I'm not able to sandbox test this problem right now. I'll have to resolve that problem before I can lay down a for-sure solution on this.

**Comment by DiamondIceNS** [comment]
My apologies for the long wait. This has finally been fixed in #62.

**Comment by ldilley** [comment]
No worries at all, @DiamondIceNS. I am just glad it got resolved. Thank you so much for the fix and the work you do on this project.
